"""
This type stub file was generated by pyright.
"""

from typing import BinaryIO, Self

class AudioSegment:
    @classmethod
    def from_file(cls, data: BinaryIO, format: str | None = ...) -> Self: ...
    def __len__(self) -> int: ...
