import { Bot20Filled, FastForward16Regular, QuestionCircle20Filled } from '@fluentui/react-icons';
import { Button } from '@/components/ui/Button';
import { SimpleTooltip } from '@/components/ui/Tooltip';
import { ReviewCommentAspects } from './ReviewCommentAspects';
import { getAccentColor, getBackgroundColor, getBorderColor, getTriangleClasses } from './utils';

function getOverallReview(state: string | undefined): JSX.Element {
  const textColor = getAccentColor(state);

  switch (state) {
    case 'positive':
      return (
        <>
          My Review is overall{' '}
          <span className='font-semibold' style={{ color: textColor }}>
            &ldquo;positive&rdquo;
          </span>
          .
        </>
      );
    case 'negative':
      return (
        <>
          My Review is overall{' '}
          <span className='font-semibold' style={{ color: textColor }}>
            &ldquo;negative&rdquo;
          </span>
          .
        </>
      );
    default:
      return <>Oops. I&apos;m unsure about how to review this. Can you review it?</>;
  }
}

type AIEvaluationReviewCommentProps = {
  summary: string | undefined;
  positiveAspects: string[] | undefined;
  negativeAspects: string[] | undefined;
  state: string | undefined;
  onImprovePrompt?: () => Promise<void>;
};

export function AIEvaluationReviewComment(props: AIEvaluationReviewCommentProps) {
  const { summary, positiveAspects, negativeAspects, state, onImprovePrompt } = props;

  const triangleOffset = state === 'positive' ? 37 : 5;

  const borderColor = getBorderColor(state);
  const backgroundColor = getBackgroundColor(state);
  const triangleClasses = getTriangleClasses(state);
  const overallReview = getOverallReview(state);

  const showOldStyleComment = !!summary && !positiveAspects && !negativeAspects;

  return (
    <div
      style={
        {
          '--triangle-offset': `${triangleOffset}px`,
          '--border-color': borderColor,
          '--background-color': backgroundColor,
        } as React.CSSProperties
      }
      className={`flex flex-col w-full flex-1 overflow-y-hidden mt-1 border rounded-[2px] mb-2 font-lato relative
        bg-[var(--background-color)]
        border-[var(--border-color)]
        ${triangleClasses}`}
    >
      <div className='flex flex-row gap-2 items-center px-3 py-2.5'>
        <SimpleTooltip content='Generated by AI'>
          <div className='flex items-center justify-center w-6 h-6 rounded-full border border-gray-300 bg-white shrink-0'>
            {state === 'unsure' ? (
              <div className='relative flex items-center justify-center'>
                <Bot20Filled className='w-4 h-4 text-gray-700' />
                <QuestionCircle20Filled className='absolute bottom-0 right-0 w-[9px] h-[9px] text-gray-900 bg-white rounded-full' />
              </div>
            ) : (
              <Bot20Filled className='w-4 h-4 text-gray-700' />
            )}
          </div>
        </SimpleTooltip>
        <div className='text-gray-700 text-[13px] font-normal'>{overallReview}</div>
      </div>
      <div className='flex w-full flex-1 flex-col bg-white overflow-y-hidden'>
        <div className='flex flex-col w-full flex-1 overflow-y-auto'>
          {state === 'negative' ? (
            <>
              <ReviewCommentAspects aspects={negativeAspects} state={'negative'} />
              <ReviewCommentAspects aspects={positiveAspects} state={'positive'} />
            </>
          ) : (
            <>
              <ReviewCommentAspects aspects={positiveAspects} state={'positive'} />
              <ReviewCommentAspects aspects={negativeAspects} state={'negative'} />
            </>
          )}
          {showOldStyleComment && (
            <div className='px-3 py-2.5 text-gray-500 text-xs whitespace-pre-line overflow-hidden transition-all duration-200 border-t border-gray-200 border-dashed'>
              {summary}
            </div>
          )}
        </div>
        {!!onImprovePrompt && (
          <div className='flex flex-row px-3 py-2 border-t border-gray-200'>
            <Button
              variant='newDesign'
              size='none'
              onClick={onImprovePrompt}
              className='w-fit px-2 py-1.5 font-semibold text-xs'
              icon={<FastForward16Regular className='w-4 h-4' />}
            >
              Send as Feedback
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}
